### ISSUE TITLE
java error when running CIRI-full.jar Merge module

### ISSUE THREAD

**Issue by iichelhadi** [bioinfo-biols/CIRI-cookbook#11]
Hi guys,
I get the following error when I try to run the Merge module.
```
Merge module start

Loading Annotation...
Annotation Loaded
Loading CIRI_AS output...
CIRI_AS output Loaded
Loading CIRI output...
CIRI output Loaded
Loading CIRI_RO output...
CIRI_RO output Loaded
Combine AS and RO output
Combine completed, 71 reads are used
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at Exon_gtf.get_exon(Exon_gtf.java:16)
        at Merge3.getmerge(Merge3.java:784)
        at CIRI_Full2.main(CIRI_Full2.java:551)
        ... 5 more
```
I have all the outputs of CIRI, prefix_jav.list and prefix_ro2_info.list. The logs are empty not errors are shown.
Hope to get a response soon.
regards

**Comment by ashleyhappiness** [comment]
@iichelhadi how did you resolve this issue? I've been running into the same issue and am not sure what to change.
