### ISSUE TITLE
java error when running CIRI_VIS

### ISSUE THREAD

**Issue by Alipe2021** [bioinfo-biols/CIRI-cookbook#13]
Hi guys,

I got an new error when running the command: `java -jar /opt/biosoft/CIRI-full_v2.0/CIRI-vis_v1.4.jar -i out_merge_circRNA_detail.anno -l output_library_length.list -r zma_dna_v4.fa -min 1 -d test_outdir -o circRNA` . I donot fix  it. Can any one help me.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at sample_MIX_all_easy4.paint(sample_MIX_all_easy4.java:1278)
        at CIRI_vis_test.main(CIRI_vis_test.java:457)
```
![图片](https://user-images.githubusercontent.com/77709930/142957662-3e0e16b8-bdc6-42e1-930c-67f455c79b75.png)

OS: opensuse 15.2
Java version:
![图片](https://user-images.githubusercontent.com/77709930/142958190-998ba35d-b463-490c-8070-307f70f7203b.png)

 CIRI-vis 1.4

**Comment by Kevinzjy** [comment]
Hi @Alipe2021 , could you try the latest version of CIRI-vis from https://github.com/bioinfo-biols/CIRI-vis ? The executable jar file is located under the `bin` directory.
