### ISSUE TITLE
CIRIquant error!

### ISSUE THREAD

**Issue by Alipe2021** [bioinfo-biols/CIRI-cookbook#15]
Hi guys,

When I ran the command:
```sh
CIRIquant --config circ_quant_cfg.yaml -1 sampleA.R1.fq.gz -2 sampleA.R2.fq.gz --bam sampleA_sorted.bam  -o ./sampleA -p sampleA  -t 8 --bed CircRNAs.bed -e CIRIquant.log
```

It got an error as follows:
```txt
[Wed 2022-03-02 20:34:12] [INFO ] Detecting FSJ reads from genome alignment file
Traceback (most recent call last):
  File "/opt/miniconda3/envs/CIRIquant_env/bin/CIRIquant", line 11, in <module>
    load_entry_point('CIRIquant==1.1.2', 'console_scripts', 'CIRIquant')()
  File "/opt/miniconda3/envs/CIRIquant_env/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/main.py", line 184, in main
    out_file = circ.proc(log_file, thread, bed_file, hisat_bam, rnaser_file, reads, outdir, prefix, anchor, lib_type)
  File "/opt/miniconda3/envs/CIRIquant_env/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/circ.py", line 656, in proc
    bsj_reads, fsj_reads = proc_genome_bam(hisat_bam, thread, circ_info, cand_bsj, anchor, circ_dir)
  File "/opt/miniconda3/envs/CIRIquant_env/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/circ.py", line 434, in proc_genome_bam
    tmp = job.get()
  File "/opt/miniconda3/envs/CIRIquant_env/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: start out of range (-1)
```
Can any one help me to solve this problem. Thanks.

**Comment by Kevinzjy** [comment]
Hi @Alipe2021, could you try running CIRIquant without the `--bam` parameter? It seems that the sampleA_sorted.bam is not generated correctly.
