### ISSUE TITLE
Bed files of CIRIquant are generated, but GTF quantitative files are not generated

### ISSUE THREAD

**Issue by Biocard** [bioinfo-biols/CIRI-cookbook#19]
Hi guys,

When I run CIRIquant, `/home/justin/miniconda2/bin/CIRIquant -t 15 \
          -1 /home/biodata/GSE135055/2.clean/SRR9856187_1_val_1.fq.gz \
          -2 /home/biodata/GSE135055/2.clean/SRR9856187_2_val_2.fq.gz  \
          --config /home/biodata/GSE135055_CIRCRNA/chr1.yml \
          -o /home/biodata/GSE135055_CIRCRNA/SRR9856187 \
          -p SRR9856187  >CIRIquant_SRR9856187.test.log`
I'm stuck at a certain step as follows:

Total time for call to driver() for forward index: 00:01:49
[Fri 2022-04-22 15:38:15] [INFO ] De novo alignment for circular RNAs ..
48182911 reads; of these:
  48182911 (100.00%) were paired; of these:
    44344044 (92.03%) aligned concordantly 0 times
    1045458 (2.17%) aligned concordantly exactly 1 time
    2793409 (5.80%) aligned concordantly >1 times
    ----
    44344044 pairs aligned concordantly 0 times; of these:
      13208 (0.03%) aligned discordantly 1 time
    ----
    44330836 pairs aligned 0 times concordantly or discordantly; of these:
      88661672 mates make up the pairs; of these:
        85158214 (96.05%) aligned 0 times
        1041907 (1.18%) aligned exactly 1 time
        2461551 (2.78%) aligned >1 times
11.63% overall alignment rate
[bam_sort_core] merging from 30 files and 15 in-memory blocks...
[Fri 2022-04-22 16:24:29] [INFO ] Detecting reads containing Back-splicing signals
[Fri 2022-04-22 16:24:59] [INFO ] Detecting FSJ reads from genome alignment file

Bed files are generated, but GTF quantitative files are not generated. No error message is reported. The specific log file is in the attachment.

Can any one help me to solve this problem. Thanks
[SRR9856187.log](https://github.com/bioinfo-biols/CIRI-cookbook/files/8546207/SRR9856187.log)
.

**Comment by Kevinzjy** [comment]
Hi @Biocard , the log file seems fine. Could you check your job scheduler system to make sure that CIRIquant did not exceed the requested memory or walltime limits?

**Comment by Biocard** [comment]
Thanks for your help @Kevinzjy. But I tried another sample and found the following error:
[Wed 2022-04-27 10:02:36] [INFO ] Input reads: SRR9856191_1_val_1.fq.gz,SRR9856191_2_val_2.fq.gz
[Wed 2022-04-27 10:02:36] [INFO ] Library type: unstranded
[Wed 2022-04-27 10:02:36] [INFO ] Output directory: /home/biodata/GSE135055_CIRCRNA/SRR9856191, Output prefix: SRR9856191
[Wed 2022-04-27 10:02:36] [INFO ] Config: GRCh38 Loaded
[Wed 2022-04-27 10:02:36] [INFO ] 20 CPU cores availble, using 20
[Wed 2022-04-27 10:02:36] [INFO ] Align RNA-seq reads to reference genome ..
[Wed 2022-04-27 11:17:29] [INFO ] Estimate gene abundance ..
[Wed 2022-04-27 11:24:25] [INFO ] No circRNA information provided, run CIRI2 for junction site prediction ..
[Wed 2022-04-27 11:24:25] [INFO ] Running BWA-mem mapping candidate reads ..
[Wed 2022-04-27 11:45:05] [INFO ] Running CIRI2 for circRNA detection ..
[Wed 2022-04-27 12:20:32] [INFO ] Extract circular sequence
[Wed 2022-04-27 12:20:53] [100% ] [##################################################]
[Wed 2022-04-27 12:20:53] [INFO ] Building circular index ..
[Wed 2022-04-27 12:22:52] [INFO ] De novo alignment for circular RNAs ..
[Wed 2022-04-27 13:27:55] [INFO ] Detecting reads containing Back-splicing signals
[Wed 2022-04-27 13:28:24] [INFO ] Detecting FSJ reads from genome alignment file
Traceback (most recent call last):
  File "/home/justin/miniconda2/bin/CIRIquant", line 10, in <module>
    sys.exit(main())
  File "/home/justin/miniconda2/lib/python2.7/site-packages/CIRIquant/main.py", line 183, in main
    out_file = circ.proc(log_file, thread, bed_file, hisat_bam, rnaser_file, reads, outdir, prefix, anchor, lib_type)
  File "/home/justin/miniconda2/lib/python2.7/site-packages/CIRIquant/circ.py", line 656, in proc
    bsj_reads, fsj_reads = proc_genome_bam(hisat_bam, thread, circ_info, cand_bsj, anchor, circ_dir)
  File "/home/justin/miniconda2/lib/python2.7/site-packages/CIRIquant/circ.py", line 434, in proc_genome_bam
    tmp = job.get()
  File "/home/justin/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
MemoryError: out of memory

All files are generated except GTF files. My processor is 128GB of ram. About how much memory is needed to run the entire task down?
[Uploading 20220427.
[20220427.log](https://github.com/bioinfo-biols/CIRI-cookbook/files/8582169/20220427.log)
log…]()
[SRR9856191.log](https://github.com/bioinfo-biols/CIRI-cookbook/files/8582170/SRR9856191.log)
