### ISSUE TITLE
Fail to run CIRIquant 

### ISSUE THREAD

**Issue by MaryamLabaf** [bioinfo-biols/CIRI-cookbook#20]
I did run CIRIquant with command:
CIRIquant -t 20 -1 /data/circRNA_fastq_files/2_S2_L001_R1_001.fastq.gz -2  /data/circRNA_fastq_files/2_S2_L001_R2_001.fastq.gz --config  /dmel_ENS_BDGP6_myCIRIquant.yml -p 2_S2 --library-type 1 and I get the following error:
[Wed 2022-06-08 12:44:20] [INFO ] Input reads: 2_S2_L001_R1_001.fastq.gz,2_S2_L001_R2_001.fastq.gz
[Wed 2022-06-08 12:44:20] [INFO ] Library type: ScriptSeq
[Wed 2022-06-08 12:44:20] [INFO ] Output directory: /home/ml98b/2_S2, Output prefix: 2_S2
[Wed 2022-06-08 12:44:20] [INFO ] Config: dmel_ENS_BDGP6 Loaded
[Wed 2022-06-08 12:44:20] [INFO ] 40 CPU cores availble, using 20
[Wed 2022-06-08 12:44:20] [INFO ] Align RNA-seq reads to reference genome ..
Traceback (most recent call last):
  File "/home/ml98b/.conda/envs/CIRI/bin/CIRIquant", line 8, in <module>
    sys.exit(main())
  File "/home/ml98b/.conda/envs/CIRI/lib/python2.7/site-packages/CIRIquant/main.py", line 152, in main
    hisat_bam = pipeline.align_genome(log_file, thread, reads, outdir, prefix)
  File "/home/ml98b/.conda/envs/CIRI/lib/python2.7/site-packages/CIRIquant/pipeline.py", line 51, in align_genome
    if os.path.getsize(sorted_bam + '.bai') <= 16:
  File "/home/ml98b/.conda/envs/CIRI/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size 
and the logFile out is:
[Wed 2022-06-08 12:44:20] [INFO ] Input reads: 2_S2_L001_R1_001.fastq.gz,2_S2_L001_R2_001.fastq.gz
[Wed 2022-06-08 12:44:20] [INFO ] Library type: ScriptSeq
[Wed 2022-06-08 12:44:20] [INFO ] Output directory: /home/ml98b/2_S2, Output prefix: 2_S2
[Wed 2022-06-08 12:44:20] [INFO ] Config: dmel_ENS_BDGP6 Loaded
[Wed 2022-06-08 12:44:20] [INFO ] 40 CPU cores availble, using 20
[Wed 2022-06-08 12:44:20] [INFO ] Align RNA-seq reads to reference genome ..
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)
/home/ml98b/.conda/envs/CIRI/bin/hisat2-align-s: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/libstdc++.so.6)
/home/ml98b/.conda/envs/CIRI/bin/hisat2-align-s: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/libstdc++.so.6)
/home/ml98b/.conda/envs/CIRI/bin/hisat2-align-s: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/libstdc++.so.6)
/home/ml98b/.conda/envs/CIRI/bin/hisat2-align-s: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/libgcc_s.so.1)
(ERR): Description of arguments failed!
Exiting now ...
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)
/home/ml98b/.conda/envs/CIRI/bin/samtools: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/ml98b/.conda/envs/CIRI/bin/../lib/./liblzma.so.5)

**Comment by Kevinzjy** [comment]
Hi @MaryamLabaf , this error means you need to update your GLIBC version (required by samtools).
