### ISSUE TITLE
Java exception when running RO2 in CIRI-Full

### ISSUE THREAD

**Issue by sgardiner01** [bioinfo-biols/CIRI-cookbook#23]
Hello,

I'm not having any problems running the CIRI-full module up until the RO2 module. At that point, I'm getting this exception:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at RO2.getro2(RO2.java:238)

Any ideas?

**Comment by felixhell2004** [comment]
Hello, I had the similar problems shown at the RO2 step.  Finally, I fixed the problem by rerun the index contrusted by bwa again.
I think the option '-a bwtsw' of bwa index is necessary.

**Comment by Kevinzjy** [comment]
Hi @felixhell2004 , empty lines in the reference fasta could also cause this error. The reference fasta should be strictly in uncompressed fasta format without any blank lines.

> Hello, I had the similar problems shown at the RO2 step. Finally, I fixed the problem by rerun the index contrusted by bwa again. I think the option '-a bwtsw' of bwa index is necessary.

**Comment by sgardiner01** [comment]
Hey @felixhell2004 and @Kevinzjy, I solved this problem by deleting the line breaks in my reference fasta to make it a single line.
