### ISSUE TITLE
CIRI-full Merge (step-by-step)

### ISSUE THREAD

**Issue by ashleyhappiness** [bioinfo-biols/CIRI-cookbook#29]
I am running into an issue running the merge function. It appears to be working but then failing during the creation of the output file. Below is the log file. I'm unsure what may be going wrong and haven't had any issues with the other steps of CIRI-full.
Thank you,
A

classpath = bin/
Output prefix = /panfs/jay/groups/5/reedkm/shared/CIRI2/Powell_Prj015/test/sample12_merge

Merge module start

Loading Annotation...
Annotation Loaded
Loading CIRI_AS output...
CIRI_AS output Loaded
Loading CIRI output...
CIRI output Loaded
Loading CIRI_RO output...
CIRI_RO output Loaded
Combine AS and RO output
Combine completed, 13 reads are used
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
	at Exon_gtf.get_exon(Exon_gtf.java:16)
	at Merge3.getmerge(Merge3.java:770)
	at CIRI_Full2.main(CIRI_Full2.java:551)
	... 5 more

**Comment by ashleyhappiness** [comment]
I still haven't been able to get this to work. I can run the test data without an issue but with my own data, it keeps failing at the Merge step. My most recent run had this feedback (I am unsure what I would need to change to get it to run):

classpath = ..//
Output prefix = /panfs/jay/groups/5/reedkm/shared/CIRI2/Powell_Prj015/CIRI-full/CIRI-full_v2.0/sample_1/sample1

Merge module start

Loading Annotation...
Annotation Loaded
Loading CIRI_AS output...
CIRI_AS output Loaded
Loading CIRI output...
CIRI output Loaded
Loading CIRI_RO output...
CIRI_RO output Loaded
Combine AS and RO output
Combine completed, 9 reads are used
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at Exon_gtf.get_exon(Exon_gtf.java:16)
        at Merge3.getmerge(Merge3.java:784)
        at CIRI_Full2.main(CIRI_Full2.java:551)
        ... 5 more
