### ISSUE TITLE
java error when running CIRI-full

### ISSUE THREAD

**Issue by iichelhadi** [bioinfo-biols/CIRI-cookbook#8]
Hi guys,
I get the following error at the Merge step of the CIRI-full script:
`Loading CIRI_AS output...
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.FileNotFoundException: /hpctmp/phaei/GSE/CIRI_full/./CIRI_full_out/SRR/CIRI-AS_output/SRR_jav.list (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at Merge3.getmerge(Merge3.java:114)
	at CIRI_Full2.main(CIRI_Full2.java:280)`

It seems to be unable to find the prefix_jav.list file. The previous  step of RO2 runs fine with no errors but the output folder CIRI-AS_output is completely empty.
Any help would be greatly appreciated

**Comment by Kevinzjy** [comment]
Hi @iichelhadi , could you show me the content of `output/CIRI_AS_error.log`?

**Comment by iichelhadi** [comment]
> Hi @iichelhadi , could you show me the content of `output/CIRI_AS_error.log`?

Hi Kevinzjy, 
thank you for  the quick response. I believe I found the issue. I think it is the gtf file that I used. the first column did not have 'chr' in front of chrom number. I re-ran with another gtf file and the pipeline seems to have worked.

**Comment by iichelhadi** [comment]
> Hi @iichelhadi , could you show me the content of `output/CIRI_AS_error.log`?

I managed to get it running. Still not sure what the issue was exactly.

**Comment by Kevinzjy** [comment]
Interesting, maybe you have run out of memory in your last run.

**Comment by iichelhadi** [comment]
sorry guys, I am running against a new issue with CIRI_full.jav
I have attached the log of "ciri_pipe_1.log" 
[ciri_pipe_1.log](https://github.com/bioinfo-biols/CIRI-cookbook/files/6929194/ciri_pipe_1.log)

It seems the issue is at the part after generating the sam file which is quite large in my case (240gb). Not sure if that is the issue but in the log I get the following error:
```
[Wed Aug  4 13:44:10 2021] CIRI finished its work. Please see output file CIRI_full_out/CIRI_output/RHC11161.ciri for detail.
Please make sure the SAM is the same one used for circRNA detection by CIRI without modification!
```
I do not modify anything. The code I used is:
```
        java -jar CIRI_full_jav/CIRI-full.jar Pipeline \
                -1 /hpctmp/phaei/patient_zero/rna_trim_fq/${line}_1_val_1.fq.gz \
                -2 /hpctmp/phaei/patient_zero/rna_trim_fq/${line}_2_val_2.fq.gz \
                -r /hpctmp/phaei/Indices/hisat_index/hisat_index_hg19/hg19.fa \
                -a /hpctmp/phaei/Indices/gencode.v19.annotation.gtf \
                -o $line \
                -d CIRI_full_out/${line} \
                -t 24
```
hope to get some help.

**Comment by Kevinzjy** [comment]
Hi @iichelhadi , CIRI-full only supports untrimmed fastq as input. Could you try running CIRI-full again with raw reads?

**Comment by iichelhadi** [comment]
> Hi @iichelhadi , CIRI-full only supports untrimmed fastq as input. Could you try running CIRI-full again with raw reads?

I see. I am afraid I don't have that data.

**Comment by iichelhadi** [comment]
> Hi @iichelhadi , CIRI-full only supports untrimmed fastq as input. Could you try running CIRI-full again with raw reads?

using the untrimmed fastq solved the issues. Thank you

**Comment by iichelhadi** [comment]
I am afraid I am getting another issue with CIRI-full
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 150
	at java.lang.String.substring(String.java:1950)
	at index_head_finder_more.<init>(index_head_finder_more.java:45)
	at RO1_single.getro1(RO1_single.java:81)
	at CIRI_Full2.main(CIRI_Full2.java:214)
	... 5 more
```
the fastq files are untrimmed.

**Comment by iichelhadi** [comment]
> Could you check whether read1 and read2 have equal lengths? The RO1 step will fail if read1 and read2 have different lengths.

I checked. not all mates have equal lengths. any way to resolve this issue?

**Comment by Kevinzjy** [comment]
> > Could you check whether read1 and read2 have equal lengths? The RO1 step will fail if read1 and read2 have different lengths.
> 
> I checked. not all mates have equal lengths. any way to resolve this issue?

Maybe try cutting all reads to a certain length like 100bp?

**Comment by iichelhadi** [comment]
> > > Could you check whether read1 and read2 have equal lengths? The RO1 step will fail if read1 and read2 have different lengths.
> > 
> > 
> > I checked. not all mates have equal lengths. any way to resolve this issue?
> 
> Maybe try cutting all reads to a certain length like 100bp?

thank you for the reply. Could you suggest a tool for that? I am trying "fastp" but it doesn't seem to be working.

**Comment by iichelhadi** [comment]
> > > Could you check whether read1 and read2 have equal lengths? The RO1 step will fail if read1 and read2 have different lengths.
> > 
> > 
> > I checked. not all mates have equal lengths. any way to resolve this issue?
> 
> Maybe try cutting all reads to a certain length like 100bp?

issues seems resolved. thank you

**Comment by iichelhadi** [comment]
Hi Kevin,
I get this error in the CIRIerror.log
`Fail to get file size for /CIRI_full_out/sam/SRR7468220_ciri.sam:  at CIRI_full_jav//bin/CIRI_v2.0.6/CIRI2.pl line 2210, <CHR1> line 64186394.`
Any idea what this could be. The script doesn't crash but continues and I do not get the necessary files to run CIRI-vis.
please help.
